### ISSUE TITLE
New tool request: add `ormolu` into the toolchain

### ISSUE THREAD

**Issue by evan0greenup** [haskell/ghcup-metadata#146]
`ormolu` is a popular Haskell formatter for developers. It would be nice to provide a static compiled `ormolu` in ghcup toolchain.

`stack install ormolu` is difficult to clean and do version management. This tool is pretty feature-completed.

**Comment by hasufell** [comment]
GHCup generally is about installing the Haskell toolchain, which is defined as:

* GHC
* cabal-install
* HLS
* stack

Right now there are no plans to extend this to other arbitrary binaries, although there was a design discussion about being able to install arbitrary binaries: https://github.com/haskell/ghcup-hs/issues/141

I've considered adding cabal-cache to ghcup simply because it's hard to bootstrap it yourself and compiling it from source defeats the purpose of it speeding up CI times. I have low appetite for formatters though. If we ever manage to come up with said installed DLS, someone else may be able to provide ormolu binaries.
